// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 bob3703
// Licensed under the Apache License, Version 2.0. See the LICENSE file for the full text.
// web/qrcode.js — minimal QR encoder, byte mode only, versions 1-4, EC levels L/M.
//
// Written for the share card so the Web UI keeps its zero-third-party property: no CDN,
// no npm install. Encodes UTF-8 text (up to 78 bytes at v4-L / 62 at v4-M — any deploy
// URL fits) and returns the module matrix for canvas drawing.
//
// Scope is deliberately narrow: byte mode only (no alphanumeric/kanji), versions 1-4
// (below v7 there are no version-info blocks), L/M only (all RS block layouts are even).
// Everything else follows ISO/IEC 18004: BCH(15,5) format info, Reed-Solomon over
// GF(256) with 0x11D, zigzag placement, and the four standard mask-penalty rules for
// auto selection. web/test-qrcode.js cross-checks every fixed-mask matrix against
// fixtures generated by the Python `qrcode` reference library
// (web/test-qrcode-fixtures.json).

const VERSIONS = {
  // version: { size, cap: max payload bytes per EC, rs: per EC [blocks, totalPerBlock, dataPerBlock], align: alignment center (0 = none) }
  1: { size: 21, cap: { L: 17, M: 14 }, rs: { L: [1, 26, 19], M: [1, 26, 16] }, align: 0 },
  2: { size: 25, cap: { L: 32, M: 26 }, rs: { L: [1, 44, 34], M: [1, 44, 28] }, align: 18 },
  3: { size: 29, cap: { L: 53, M: 42 }, rs: { L: [1, 70, 55], M: [1, 70, 44] }, align: 22 },
  4: { size: 33, cap: { L: 78, M: 62 }, rs: { L: [1, 100, 80], M: [2, 50, 32] }, align: 26 },
};

// ---------------------------------------------------------------- GF(256), poly 0x11D
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

function gmul(a, b) {
  return a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]];
}

// Generator polynomial, highest degree first, monic (gen[0] === 1).
function rsGenerator(degree) {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= gmul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

function rsRemainder(dataBlocks, ecLen) {
  const gen = rsGenerator(ecLen);
  return dataBlocks.map((block) => {
    const rem = new Uint8Array(ecLen);
    for (const byte of block) {
      const factor = byte ^ rem[0];
      rem.copyWithin(0, 1);
      rem[ecLen - 1] = 0;
      if (factor !== 0) {
        for (let i = 0; i < ecLen; i++) rem[i] ^= gmul(gen[i + 1], factor);
      }
    }
    return Array.from(rem);
  });
}

// ---------------------------------------------------------------- bit stream + interleaving
export function buildCodewords(text, spec, ecLevel, ecLen) {
  const bytes = Array.from(new TextEncoder().encode(text));
  if (bytes.length > spec.cap[ecLevel]) {
    throw new Error(`QR: payload is ${bytes.length} bytes, exceeds ${spec.cap[ecLevel]} (${ecLevel})`);
  }
  const bits = [];
  const push = (value, count) => {
    for (let i = count - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };
  push(0b0100, 4); // byte mode indicator
  push(bytes.length, 8); // character count (8 bits for versions 1-9)
  bytes.forEach((b) => push(b, 8));
  push(0, Math.min(4, 8 - (bits.length % 8))); // terminator: up to 4 zero bits
  while (bits.length % 8 !== 0) bits.push(0); // byte alignment
  const data = [];
  for (let i = 0; i < bits.length; i += 8) {
    let b = 0;
    for (let j = 0; j < 8; j++) b = (b << 1) | bits[i + j];
    data.push(b);
  }
  const [blocks, totalPerBlock, dataPerBlock] = spec.rs[ecLevel];
  const totalData = dataPerBlock * blocks;
  for (let pad = 0xec; data.length < totalData; pad = pad === 0xec ? 0x11 : 0xec) data.push(pad);

  const dataBlocks = [];
  for (let b = 0; b < blocks; b++) dataBlocks.push(data.slice(b * dataPerBlock, (b + 1) * dataPerBlock));
  const ecBlocks = rsRemainder(dataBlocks, ecLen);

  const out = [];
  for (let i = 0; i < dataPerBlock; i++) dataBlocks.forEach((blk) => out.push(blk[i]));
  for (let i = 0; i < ecLen; i++) ecBlocks.forEach((blk) => out.push(blk[i]));
  return out;
}

// ---------------------------------------------------------------- format info (BCH 15,5)
const G15 = 0x537;
const G15_MASK = 0x5412;
const EC_BITS = { L: 0b01, M: 0b00 };

function bchDigit(value) {
  let d = 0;
  while (value !== 0) {
    d++;
    value >>>= 1;
  }
  return d;
}

function formatBits(ecLevel, mask) {
  const data = (EC_BITS[ecLevel] << 3) | mask;
  let d = data << 10;
  while (bchDigit(d) - bchDigit(G15) >= 0) {
    d ^= G15 << (bchDigit(d) - bchDigit(G15));
  }
  return ((data << 10) | d) ^ G15_MASK;
}

// ---------------------------------------------------------------- masks + penalty
const MASKS = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

// ISO/IEC 18004 penalty rules N1-N4, lower is better.
function maskPenalty(modules, size) {
  let penalty = 0;
  // N1: runs of >= 5 same-colour modules, rows and columns
  for (let axis = 0; axis < 2; axis++) {
    for (let i = 0; i < size; i++) {
      let run = 1;
      for (let j = 1; j < size; j++) {
        const cur = axis === 0 ? modules[i][j] : modules[j][i];
        const prev = axis === 0 ? modules[i][j - 1] : modules[j - 1][i];
        if (cur === prev) {
          run++;
        } else {
          if (run >= 5) penalty += 3 + (run - 5);
          run = 1;
        }
      }
      if (run >= 5) penalty += 3 + (run - 5);
    }
  }
  // N2: 2x2 blocks of the same colour
  for (let r = 0; r < size - 1; r++) {
    for (let c = 0; c < size - 1; c++) {
      const v = modules[r][c];
      if (v === modules[r][c + 1] && v === modules[r + 1][c] && v === modules[r + 1][c + 1]) penalty += 3;
    }
  }
  // N3: 1011101 with 0000 on either side, both directions
  const patternA = [true, false, true, true, true, false, true, false, false, false, false];
  const patternB = [false, false, false, false, true, false, true, true, true, false, true];
  const matchesAt = (get) => {
    let count = 0;
    for (let i = 0; i < size; i++) {
      for (let j = 0; j + 11 <= size; j++) {
        let a = true, b = true;
        for (let k = 0; k < 11; k++) {
          const v = get(i, j + k);
          if (v !== patternA[k]) a = false;
          if (v !== patternB[k]) b = false;
          if (!a && !b) break;
        }
        if (a) count++;
        if (b) count++;
      }
    }
    return count;
  };
  penalty += matchesAt((r, c) => modules[r][c]) * 40;
  penalty += matchesAt((r, c) => modules[c][r]) * 40;
  // N4: dark-module ratio deviation from 50%
  let dark = 0;
  for (let r = 0; r < size; r++) for (let c = 0; c < size; c++) if (modules[r][c]) dark++;
  const ratio = (dark * 100) / (size * size);
  penalty += Math.floor(Math.abs(ratio - 50) / 5) * 10;
  return penalty;
}

// ---------------------------------------------------------------- matrix construction
function buildMatrix(spec, ecLevel, mask, codewords) {
  const size = spec.size;
  const modules = Array.from({ length: size }, () => new Array(size).fill(null));
  const inBounds = (r, c) => r >= 0 && r < size && c >= 0 && c < size;

  // finder patterns (7x7) + separators (the surrounding ring stays light)
  const finder = (row, col) => {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const rr = row + r, cc = col + c;
        if (!inBounds(rr, cc)) continue;
        const inCore = r >= 0 && r <= 6 && c >= 0 && c <= 6;
        if (!inCore) {
          modules[rr][cc] = false; // separator
        } else {
          modules[rr][cc] = (r === 0 || r === 6 || c === 0 || c === 6) || (r >= 2 && r <= 4 && c >= 2 && c <= 4);
        }
      }
    }
  };
  finder(0, 0);
  finder(0, size - 7);
  finder(size - 7, 0);

  // timing patterns
  for (let i = 8; i < size - 8; i++) {
    if (modules[6][i] === null) modules[6][i] = i % 2 === 0;
    if (modules[i][6] === null) modules[i][6] = i % 2 === 0;
  }

  // alignment pattern (single 5x5, versions 2+; the overlapping ones are inside finders already)
  if (spec.align) {
    const a = spec.align;
    for (let r = -2; r <= 2; r++) {
      for (let c = -2; c <= 2; c++) {
        modules[a + r][a + c] = Math.max(Math.abs(r), Math.abs(c)) !== 1;
      }
    }
  }

  // reserve format-info cells + the dark module
  for (let i = 0; i <= 8; i++) {
    if (i !== 6) {
      if (modules[8][i] === null) modules[8][i] = false;
      if (modules[i][8] === null) modules[i][8] = false;
    }
  }
  for (let i = 0; i < 8; i++) {
    if (modules[8][size - 1 - i] === null) modules[8][size - 1 - i] = false;
    if (modules[size - 1 - i][8] === null) modules[size - 1 - i][8] = false;
  }
  modules[size - 8][8] = true; // dark module

  // data into the remaining null cells, zigzag from bottom-right, skipping column 6
  const maskFn = MASKS[mask];
  let inc = -1;
  let row = size - 1;
  let bitIndex = 7;
  let byteIndex = 0;
  for (let col = size - 1; col > 0; col -= 2) {
    if (col === 6) col--;
    for (;;) {
      for (let c = 0; c < 2; c++) {
        if (modules[row][col - c] === null) {
          let dark = false;
          if (byteIndex < codewords.length) dark = ((codewords[byteIndex] >>> bitIndex) & 1) === 1;
          if (maskFn(row, col - c)) dark = !dark;
          modules[row][col - c] = dark;
          bitIndex--;
          if (bitIndex === -1) {
            byteIndex++;
            bitIndex = 7;
          }
        }
      }
      row += inc;
      if (row < 0 || row >= size) {
        row -= inc;
        inc = -inc;
        break;
      }
    }
  }

  // format info, two copies
  const bits = formatBits(ecLevel, mask);
  for (let i = 0; i < 15; i++) {
    const dark = ((bits >> i) & 1) === 1;
    if (i < 6) modules[i][8] = dark; // copy 1: around the top-left finder
    else if (i < 8) modules[i + 1][8] = dark;
    else modules[size - 15 + i][8] = dark; // below the bottom-left finder
  }
  for (let i = 0; i < 15; i++) {
    const dark = ((bits >> i) & 1) === 1;
    if (i < 8) modules[8][size - 1 - i] = dark; // copy 2: left of the top-right finder
    else if (i < 9) modules[8][15 - i] = dark;
    else modules[8][14 - i] = dark; // split around the top-left finder
  }
  modules[size - 8][8] = true; // re-assert the dark module

  return modules;
}

/**
 * Encode `text` into a QR matrix.
 * opts.ec: 'L' | 'M' (default 'M'); opts.mask: 0-7 to force one, otherwise auto-select
 * by the standard penalty rules (ties keep the lowest mask id).
 * Returns { size, modules } where modules[r][c] is true for dark.
 */
export function qrMatrix(text, opts = {}) {
  const ecLevel = opts.ec === 'L' ? 'L' : 'M';
  const payload = new TextEncoder().encode(text).length;
  let spec = null;
  for (const v of [1, 2, 3, 4]) {
    if (payload <= VERSIONS[v].cap[ecLevel]) {
      spec = VERSIONS[v];
      break;
    }
  }
  if (!spec) throw new Error(`QR: payload is ${payload} bytes, exceeds 78 (L) / 62 (M) at version 4`);
  const [, , dataPerBlock] = spec.rs[ecLevel];
  const ecLen = spec.rs[ecLevel][1] - dataPerBlock;
  const codewords = buildCodewords(text, spec, ecLevel, ecLen);
  const candidates = opts.mask >= 0 ? [opts.mask] : [0, 1, 2, 3, 4, 5, 6, 7];
  let best = null;
  for (const mask of candidates) {
    const modules = buildMatrix(spec, ecLevel, mask, codewords);
    const penalty = opts.mask >= 0 ? 0 : maskPenalty(modules, spec.size);
    if (best === null || penalty < best.penalty) best = { size: spec.size, modules, penalty };
  }
  return { size: best.size, modules: best.modules };
}
